@PasswordManager.Web.Client_HostAddress = http://localhost:5047

POST {{PasswordManager.Web.Client_HostAddress}}/api/account/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###
